global:
  ingress:
    className: nginx
    certManager:
      issuerEmail: me@example.com
    domains:
      - myhost-check.info

# Nginx ingress configuration -------------------------------------------------
# This needs to be enabled, if you don't have nginx-ingress installed already
# in your cluster.
ingress-nginx:
  enabled: false

# cert-manager configuration --------------------------------------------------
# Disable cert-manager and certIssuer for local testing, they are not required.
# Nginx ingress will create a self-signed certificate for testing automatically.

# If you want to try out cert-manager, make sure install CRDs BEFORE you install the chart.
# Make sure to enable certIssuer and configure ingress settings accordingly, see above.
# For local testing issuerType = namespace and issuerName = self-signed is recommended.
# (see here: https://cert-manager.io/docs/installation/helm/#3-install-customresourcedefinitions )
cert-manager:
  enabled: false

certIssuer:
  enabled: false

# ckan configuration ----------------------------------------------------------
ckan:
  enabled: true

  persistence:
    enabled: false

  siteUrl: https://myhost-check.info
  
  siteTitle: My CKAN instance THE BASE VERSION, GISLAB AUGSBURG
  # -- [CKAN config site_id](https://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-site-id)
  siteId: default
  # -- [CKAN config site_id](https://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-site-description)
  siteDescription: This is my CKAN instance for stuff. THE BASE VERSION, GISLAB AUGSBURG
  # -- CKAN config intro text](https://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-site-intro-text)
  siteIntroText: This is the intro to my CKAN instance. THE BASE VERSION, GISLAB AUGSBURG
  # -- Path to CKAN site logo image. Custom logos will usually be located in `/webassets/`.
  # See `webassets.path` setting.
  # [CKAN config site_id](https://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-site-logo)
  siteLogo: /base/images/ckan-logo.png
  # -- [CKAN config about](https://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-site-about)
  siteAbout: My CKAN about info. THE BASE VERSION, GISLAB AUGSBURG

  # Startup -------------------------------------------------------------------
  # Depending on the hardware and configuration of you minikube cluster the
  # startup ofCKAN may be slow. Thus, the default settings for the startup
  # check may be too strict and `failureThreshold` needs to be increased.
  startup:
    # -- Inital delay seconds for the startup probe.
    initialDelaySeconds: 60
    # -- Check interval for the startup probe
    periodSeconds: 10
    # -- Failure threshold for the startup probe
    failureThreshold: 60
    # -- Timeout interval for the startup probe
    # Note: The CKAN pod may take some time to startup on slow systems, e.g. one
    # testing clusters. Make sure to set this value high enough to avoid the pod
    # being restarted before it has fully initialized.
    timeoutSeconds: 10
